name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use the version your app needs
          distribution: 'temurin'

      # Step 3: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Move the .jar file to the root of the project
      - name: Prepare deployment package
        run: |
          mv target/*.jar application.jar
          zip -r app.zip application.jar

      # Step 5: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          application_name: user-address-mgmt
          environment_name: User-address-mgmt-env
          region: us-east-1
          version_label: build-${{ github.run_number }}
          deployment_package: app.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
